app/models/__init__.py
from .quiz import Question,AnswerType

__all__ = [
    Question,
    AnswerType
]

app/models/quiz.py
# Local modules
from app.extensions import db
from app.utils.models import generate_uuid
from enum import Enum
from sqlalchemy import Enum as SQLAlchemyEnum


class AnswerType(Enum):
    single_line = "single_line"
    choice = "choice"
    yes_no = "yes_no"


class Question(db.Model):
    id = db.Column(db.String, primary_key=True, default=generate_uuid, unique=True, nullable=False)
    queue = db.Column(db.Integer, nullable=False)
    text = db.Column(db.Text, nullable=False)
    answer_type = db.Column(SQLAlchemyEnum(AnswerType), nullable=False)
    a = db.Column(db.String(255))
    b = db.Column(db.String(255))
    c = db.Column(db.String(255))
    d = db.Column(db.String(255))
    ans = db.Column(db.String(255))

    def __repr__(self):
        return f"<Question {self.text}>"

app/utils/models.py
# Other modules
import json
import uuid


class SerializableClass:
    def to_json(self):
        return json.dumps(self.to_dict())

    def __str__(self):
        return self.to_json()

    def to_dict(self):
        return self.__dict__

    @staticmethod
    def is_serializable(obj):
        """
        Check if an object is serializable.

        Parameters:
            obj (Any): The object to be checked.

        Returns:
            bool: True if the object is serializable, False otherwise.
        """
        try:
            json.dumps(obj)
            return True
        except:
            return False


def shorten_uuid(input_uuid: uuid.UUID, length: int = 24) -> str:
    """
    Shortens a UUID to a specified length by converting it to a hexadecimal string and truncating it.

    Parameters:
        input_uuid (uuid.UUID): The UUID to be shortened.
        length (int): The desired length of the shortened UUID. Defaults to 24.

    Returns:
        str: The shortened UUID as a hexadecimal string.
    """
    # Convert UUID to a hexadecimal string
    str_uuid = str(input_uuid)
    hex_uuid = str_uuid.replace("-", "")

    # Truncate to the desired length
    truncated_hex = hex_uuid[:length]

    return truncated_hex


def generate_uuid(length: int = None) -> str:
    """
    Generate a universally unique identifier (UUID) as a string.

    Parameters:
        length (int, optional): The length of the shortened UUID. Defaults to None.

    Returns:
        str: The generated UUID as a string.

    Example:
        >>> generate_uuid()
        'dfc6f4a9-2a97-4c1c-9a04-9b09c6e4b7be'
        >>> generate_uuid(8)
        'dfc6f4a9'
    """
    if length:
        return shorten_uuid(uuid.uuid4())

    str_uuid = str(uuid.uuid4())
    return str_uuid

app/forms/quiz.py
# Flask modules
from flask_wtf import FlaskForm
from wtforms import SubmitField, RadioField
from wtforms.validators import DataRequired


class QuestionForm(FlaskForm):
    options = RadioField("Options: ", validators=[DataRequired()], default=1)
    submit = SubmitField("Next")

app/__init__.py
# Flask modules
from flask import Flask

# Other modules
import os


def create_app(debug: bool = False):
    # Check if debug environment variable was passed
    FLASK_DEBUG = os.environ.get("FLASK_DEBUG", False)
    if FLASK_DEBUG:
        debug = FLASK_DEBUG

    # Create the Flask application instance
    app = Flask(
        __name__,
        template_folder="../templates",
        static_folder="../static",
        static_url_path="/",
    )

    # Set current_app context
    app.app_context().push()

    if debug:
        from app.config.dev import DevConfig

        app.config.from_object(DevConfig)
    else:
        from app.config.prod import ProdConfig

        app.config.from_object(ProdConfig)

    # Uncomment to enable logger
    # from app.utils.logger import setup_flask_logger
    # setup_flask_logger()

    # Initialize extensions
    from app.extensions import db, cors, cache, limiter

    db.init_app(app)
    cors.init_app(app)
    cache.init_app(app)
    limiter.init_app(app)

    # Import all models and Create database tables
    from app import models

    db.create_all()

    # Register blueprints or routes
    from app.routes import quiz_bp, pages_bp

    app.register_blueprint(quiz_bp)
    app.register_blueprint(pages_bp)

    # Global Ratelimit Checker
    # this is used because auto_check is set to 'False'
    app.before_request(lambda: limiter.check())

    return app

app/extensions/__init__.py
from .db import db
from .cors import cors
from .cache import cache
from .limiter import limiter

app/routes/__init__.py
from .quiz import quiz_bp
from .pages import pages_bp

app/routes/pages/__init__.py
# Flask modules
from flask import Blueprint

# Blueprint modules
from .core import core_bp

pages_bp = Blueprint("pages", __name__, url_prefix="/")


pages_bp.register_blueprint(core_bp)

app/routes/quiz/__init__.py
import random

# Flask modules
from flask import Blueprint, redirect, url_for, flash, render_template, request, session

# Local modules
from app.models.quiz import Question, AnswerType
from app.extensions import db, limiter
from app.forms.quiz import QuestionForm

quiz_bp = Blueprint("quiz", __name__, url_prefix="/quiz")


@quiz_bp.route("/", methods=["GET", "POST"])
def quiz_question_list():

    questions = Question.query.all()
    random_questions = random.sample(questions, min(5, len(questions)))
    highest_score = session.get("highest_score", 0)

    if request.method == "POST":
        score = 0
        for answered_question_key, user_answer in request.form.items():
            question_id = answered_question_key.split("question-")[-1]
            question_obj = Question.query.filter_by(id=question_id).first()
            if question_obj.ans == user_answer:
                score += 20

        if score > highest_score:
            session["highest_score"] = score

        flash(f"Your score is {score}")
        return redirect(url_for("pages.core.home_route"))

    return render_template("quiz/index.html", questions=random_questions, answer_type=AnswerType, highest_score=highest_score)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/images/favicon.ico" />
    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    {% block customCss %}

    {% endblock %}

    <title>
      {% block title %}

      {% endblock %}
    </title>
  </head>
  <body class="bg-gray-100 dark:text-white dark:bg-gray-800">
    {% block content %}

    {% endblock %}

    <div class="container">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24">
              <use xlink:href="#bootstrap"></use>
            </svg>
          </a>
          <span class="mb-3 mb-md-0 text-muted">© 2024 Yasin Çakır</span>
        </div>
      </footer>
    </div>

    <!-- Include Bootstrap JS -->
    <script src="/js/main.js" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% block customJs %}

    {% endblock %}
  </body>
</html>

templates/pages/home.html
{% extends 'base.html' %}

{% block customCss %}
  <link rel="stylesheet" href="/css/main.css" />
{% endblock %}

{% block title %}
  Home
{% endblock %}

{% block content %}
  <!-- Flash mesajlarını göster -->
  {% with messages=get_flashed_messages(with_categories=True) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="flash-message {{ category }}">{{ message }}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <nav class="nav">
    <input id="menu" type="checkbox" />
    <label for="menu">Menu</label>
    <ul class="menu">
      <li>
        <a href="{{ url_for('pages.core.home_route') }}">
          <span>Anasayfa</span>
          <i class="fas fa-address-card" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="{{ url_for('quiz.quiz_question_list') }}">
          <span>Quiz</span>
          <i class="fas fa-tasks" aria-hidden="true"></i>
        </a>
      </li>
    </ul>
  </nav>
  
{% endblock %}

templates/quiz/index.html
{% extends 'base.html' %}

{% block customCss %}
  <link rel="stylesheet" href="/css/quiz.css" />
{% endblock %}

{% block title %}
  Quiz Page
{% endblock %}

{% block content %}
  <div class="quiz-container">
    <div class="row">
      <div class="col-11"><h1>Quiz</h1></div>
      <div class="col-1">High Score <span class="badge badge-success">{{highest_score}}%</span></div>
    </div>
    
    <form method="POST">
      {% for question in questions %}
        <div class="question-block">
          <p>
            <strong>{{ loop.index }}. {{ question.text }}</strong>
          </p>
          {% if answer_type.single_line == question.answer_type %}
            <input required type="text" name="question-{{ question.id }}" size="50" /><br />
          {% elif answer_type.choice == question.answer_type %}
            <label><input required type="radio" name="question-{{ question.id }}" value="{{ question.a }}" /> {{ question.a }}</label><br />
            <label><input required type="radio" name="question-{{ question.id }}" value="{{ question.b }}" /> {{ question.b }}</label><br />
            <label><input required type="radio" name="question-{{ question.id }}" value="{{ question.c }}" /> {{ question.c }}</label><br />
            <label><input required type="radio" name="question-{{ question.id }}" value="{{ question.d }}" /> {{ question.d }}</label><br />
          {% elif answer_type.yes_no == question.answer_type %}
            <label><input required type="radio" name="question-{{ question.id }}" value="yes" />Yes</label><br />
            <label><input required type="radio" name="question-{{ question.id }}" value="no" />No</label><br />
          {% endif %}
        </div>
      {% endfor %}
      <button type="submit">Submit</button>
    </form>
  </div>
{% endblock %}